name: http_practice
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  cached_network_image: ^3.2.1
  build_runner: ^2.2.0
  provider: ^6.0.3
  fluttertoast: ^8.0.9
  connectivity_plus: ^2.3.6
  firebase_core: ^1.20.0
  firebase_auth: ^3.5.0
  dropdown_button2: ^1.6.3
  shimmer: ^2.0.0
  expand_tap_area: ^1.1.1
  dio: ^4.0.6
  json_serializable: ^6.3.2
  json_annotation: ^4.6.0
  freezed: ^2.1.1
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  flare_flutter: ^3.0.2
  path_provider: ^2.0.9
  flutter_svg: ^1.0.3
  http: ^0.13.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/


